### ISSUE TITLE
Adição de Modal para o Card de "Pequenos Pecados" [60pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPayBCW20#16]
Com base nos cartões utilizados na landpage devemos estruturar modais largos como prevê a documentação para apresentar material para os 3 cards da página inicial. Lembrando que somente no modal que o título esta no texto entre aspas da tarefa.
Documentação de uso do Bootstrap em Modal Large
![image](https://user-images.githubusercontent.com/31005408/164029977-50b66597-cc0a-4c83-8896-719902c11af3.png)
Modal implementado com base sistema da landpage:
![image](https://user-images.githubusercontent.com/31005408/164030210-0987ccfb-89cf-4d25-8de7-ee587b411b61.png)
os links devem estar em botões ou nas imagens para abrir o modal. Use com criatividade o recurso de modal.

![Image](https://user-images.githubusercontent.com/31005408/170556375-6b93215e-2f1f-48a8-b6ed-861dce96f91f.png)

![Image](https://user-images.githubusercontent.com/31005408/170556393-a2f6e310-57f8-4897-9e21-ace836d39591.png)

**Comment by soulcode-acad** [comment]
Tem certeza que estes cartões estão corretamente alocados consultem o @victoricoma por favor ou os @renato3x e @TatianaDChiacchio .... 
![image](https://user-images.githubusercontent.com/100297907/170735319-e59b1fe9-b3b8-45a8-a0b9-461f51e30027.png)

**Comment by soulcode-acad** [comment]
Pessoal cadê as PRs destas entregas? Cadê o anexo destas tarefas? Lembrando que cada 1) Demanda => 1) Entrega CI/CD [falta os anexos deste cartão!]

![image](https://user-images.githubusercontent.com/100297907/171031760-155bdb2f-1089-48ae-860f-c18137505599.png)

![image](https://user-images.githubusercontent.com/100297907/171031933-1a4ba9ee-bb7a-4070-812f-e8b7e8a0e703.png)
