### ISSUE TITLE
Adição de Carrossel de Cartões [60pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPayBCW20#23]
Colocar a estrutura de cards dentro de um carrossel de acordo com a documentação do Bootstrap assim implementando o avançar dos grupos de cartões de 3 em 3.

Exemplo de Adição Visual
![image](https://user-images.githubusercontent.com/31005408/164033290-05b7209b-d9c2-46ad-ab28-51683cc6c6f2.png)

Documentação do Bootstarp
![image](https://user-images.githubusercontent.com/31005408/164033360-518fb7c0-0e82-461b-a125-da7ebec0095f.png)

Informações de Texto dos cartões: (Não precisa usar em objeto só os textos.)
const cards = [
  {
    id: 1001,
    img: "../img/1.png",
    title: "Planejamento Sempre",
    body: "Aqui você poderá designar cada parte dos seus rendimentos e planejar para que seu dinheiro posso sempre cuidar mais de você.",
    date: "17 de dezembro 2021",
    categoria: "bloco1",
  },
  {
    id: 1002,
    img: "../img/2.png",
    title: "Redes Sociais",
    body: "Apoie nosso aplicativo seguindo nas redes sociais. No facebook nossa comunidade tem dicas exclusivas para gerenciar os gastos e economizar em coisas pequenas e sem dor no bolso.",
    date: "17 de dezembro 2021",
    categoria: "bloco1",
  },
  {
    id: 1003,
    img: "./img/3.png",
    title: "Venha e Faça Parte",
    body: " o Time de desenvolvimento do goodpay é composto por desenvolvedores do BCW 9 da Soul Code Academy venha fazer parte da nossa equipe desenvolvendo suas próprias aplicações.",
    date: "17 de dezembro 2021",
    categoria: "bloco1",
  },
  {
    id: 1004,
    img: "../img/4.png",
    title: "Money for Live",
    body: "Com os planos de economia para sair no rolê, marque sua data de saida e só guarde em seu cofre todos os meses se você for sorteado ganha 5x o que tiver em seu cofrinho para dar aquele UP na suas férias.",
    date: "23 de dezembro 2021",
    categoria: "bloco2",
  },
  {
    id: 1005,
    img: "../img/5.png",
    title: "Black Friday",
    body: "Todos os planos do GoodPay com 50% de descontos só não tem desconto quem não quer. Esta promoção é valida até dia 6 de janeiro de 2022 e somente para os planos que não tem sorteios e capitalização premiada.",
    date: "23 de dezembro 2021",
    categoria: "bloco2",
  },
  {
    id: 1006,
    img: "../img/6.png",
    title: "Plano de Educação",
    body: "Comece a economizar assim que seu filho nascer e concorra todo ano á premios percentuais de seu porquinho e se seu beneficiado tirar nota superior à 800 no Mec Enem ganhe 3x do seu porquinho na hora para turbinar o prêmio pelo esforço dele.",
    date: "23 de dezembro 2021",
    categoria: "bloco2",
  },
  {
    id: 1007,
    img: "../img/7.png",
    title: "Pequenos Pecados",
    body: "Ao economizar 250 reais e seu cofrinho o GoodPay lhe dará um vale café e um vale rosquinha para premiar seu empenho em guardar. Vire um guardador e ainda tenho um pequeno prazer no final do mês.",
    date: "27 de dezembro 2021",
    categoria: "bloco3",
  },
  {
    id: 1008,
    img: "../img/8.png",
    title: "GoodPay no cartão",
    body: "Se economizar 250 reais por mês em seu porquinho de comprovar a redução de 15% ou mais na fatura de seu cartão o GoodPay vai te dar 300% do CDI em seu porquino de acordo com o valor que estiver nele. Reduz o cartão e ganha o CDI.",
    date: "27 de dezembro 2021",
    categoria: "bloco3",
  },
  {
    id: 1009,
    img: "../img/9.png",
    title: "GoodPay no Cash Back",
    body: "Todas as compras a vista que não são vinculadas ao seu especial podem render bilhetes para sorteios. Economize 250 no mês e faça compras no cartão de débito sem usar o especial ao final terá bilhetes que podem render desde um voucher de sanduba até 8x seu porquinho.",
    date: "27 de dezembro 2021",
    categoria: "bloco3",
  },
];
export default cards;

**Comment by soulcode-acad** [comment]
Tem certeza que estes cartões estão corretamente alocados consultem o @victoricoma por favor ou os @renato3x e @TatianaDChiacchio .... 
![image](https://user-images.githubusercontent.com/100297907/170735319-e59b1fe9-b3b8-45a8-a0b9-461f51e30027.png)
