### ISSUE TITLE
Adição da Página de promoções [60pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPayBCW20#6]
Ao clicar em cada uma das imagens do banner levar para uma página onde se resume todas as páginas e informações das promoções do banner, neste caso poderá ser utilizado um arquivo com nome promo.html ou um modal sobre visualização.
![image](https://user-images.githubusercontent.com/31005408/164013643-e21b528c-792f-4ccd-af42-0235758c1dbf.png)
![image](https://user-images.githubusercontent.com/31005408/164013660-444326a5-a944-400a-b24f-7e0b63c2acb5.png)
![image](https://user-images.githubusercontent.com/31005408/164013758-baaa1eaf-621d-49da-a0fc-e9ae41fc2c6a.png)
![image](https://user-images.githubusercontent.com/31005408/164017925-a7c43443-ca90-4ece-bfdb-e775b24253fc.png)

**Comment by estersilvade** [comment]
- [ ] A Pagina de  promoção Foi usada para desenvolvimento de aprendizado de participantes que não tinha  experiência
- [ ] Com toda a orientação dos outros participantes  subimos esta  versão para que vejam  a evolução  delas 
- [ ]  ainda temos  mais duas versão
