### ISSUE TITLE
Toast de aviso com link para LGPD de uso de informações e cookies do site (urgente) [90pts]

### ISSUE THREAD

**Issue by soulcode-acad** [victoricoma/GoodPayBCW20#65]
Com uso de Toast para avisar do uso de informações para cliente para adequação para LGPD. Exemplos dee toast em bootstrap [https://getbootstrap.com/docs/5.0/components/toasts/], regras gerais para fundamentos da criação de uso da informação [http://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm]

**Comment by soulcode-acad** [comment]
Olá @victoricoma devido ao fim de prazo para adequação, solicitamos que essa atualização da aplicação seja urgente, já que pode gerar prejuízos se o cliente não for capaz de ter ciência dos termos de uso das informações do site.

**Comment by victoricoma** [comment]
> Olá @victoricoma devido ao fim de prazo para adequação, solicitamos que essa atualização da aplicação seja urgente, já que pode gerar prejuízos se o cliente não for capaz de ter ciência dos termos de uso das informações do site.

Opa pode deixar o @ferlicio está em desenvolvimento e entrar na fila de entregas assim que ele terminar!
